config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, only: [:new, :create, :index]

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(params_post)

    @post.user = current_user

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def params_post
    params.require(:post).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% unless current_user %>
  <div class="index-header-not-logged-in">
    <%= button_to "sign up", new_user_registration_path, method: :get, class: "button" %>
    <%= button_to "login", new_user_session_path, method: :get, class: "button" %>
  </div>
<% end %><br/><br/>
    <%= yield %>
    
</html>

app/views/posts/index.html.erb
<% if current_user %>
  <div class="index-header-logged-in">
    <div class="username">
      <%= current_user.username %>
    </div>
    <div class="index-header-logged-in">
      <%= button_to "make a new post", new_post_path, method: :get, class: "button" %>
      <%= button_to "logout", destroy_user_session_path, method: :delete, class: "button" %>
    </div>
  </div>
<% end %>
<h1>All of the posts</h1>
<div class="post-boxes-container">
  <% @posts.each do |post| %>
    <div class="post-box">
      <div class="username-in-post-box">
        <% if current_user %>
          <%= post.user.username %>
        <% end %>
      </div><br>
      <div class="body-in-post-box">
        "<%= post.text %>"
      </div><br>
      <div class="timestamp-in-post-box">
        <%= time_ago_in_words(post.created_at) %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="just-back-button-header">
    <%= button_to "back to posts", root_path, method: :get, class: "button" %>
</div>

<%= form_with model: @post, class: "post-form" do |form| %>
  <%= form.label "Write a post!", class: "label" %>
  <%= form.text_area :text, class: "text-area" %>
  <%= form.submit "Post it!", class: "submit" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>